/* eslint-disable import/no-duplicates */
/* import the fontawesome core */
import { library } from '@fortawesome/fontawesome-svg-core'

/* import specific icons */
/* to limit the size of the final project you import individal icons */
/* NOTE: you also have to load them below by adding to the library */
import {
  faRobot,
  faSwatchbook,
  faDesktop,
  faUserSecret,
  faQrcode,
  faDownload,
  faGear,
  faBook,
  faBan,
  faTrash,
  faHouseFlag,
  faClock,
  faCloudArrowUp,
  faArrowsTurnToDots,
  faArrowRotateLeft,
  faExplosion,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowsUpDownLeftRight,
  faArrowDown,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faCheck,
  faSquareCheck,
  faDatabase,
  faRainbow,
  faHouse,
  faDice,
  faFaceLaughBeam,
  faGlobe,
  faPenToSquare,
  faClipboard,
  faHand,
  faMagnifyingGlass,
  faCircleXmark,
  faCircleMinus,
  faBahai,
  faFaceGrinWide,
  faShapes,
  faImage,
  faSackDollar,
  faFlask,
  faCircle,
  faCircleDot,
  faCircleChevronLeft,
  faSquareXmark,
  faThumbtack,
  faPencil,
  faChartLine,
  faEye,
  faUserMinus,
  faUserPlus,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faSquareUpRight,
  faXmark,
  faAnglesRight,
  faAnglesLeft,
  faHammer,
  faSquareCaretRight,
  faCodeBranch,
  faMagnifyingGlassArrowRight,
  faLeaf,
  faPerson,
} from '@fortawesome/free-solid-svg-icons'

import { faCircle as farCircle, faClock as farClock } from '@fortawesome/free-regular-svg-icons'

import { faDiamond } from '@fortawesome/free-solid-svg-icons'

/* add icons to the library */
library.add(
  faRobot,
  faSwatchbook,
  faDesktop,
  farCircle,
  faTrash,
  faHouseFlag,
  faLeaf,
  faBan,
  faCircleChevronLeft,
  faQrcode,
  faDownload,
  faCloudArrowUp,
  faClock,
  farClock,
  faCodeBranch,
  faSquareCaretRight,
  faCheck,
  faXmark,
  faUserSecret,
  faSquareUpRight,
  faGear,
  faBook,
  faArrowsTurnToDots,
  faArrowRotateLeft,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faExplosion,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faArrowsUpDownLeftRight,
  faSquareCheck,
  faDatabase,
  faFaceLaughBeam,
  faGlobe,
  faHand,
  faMagnifyingGlass,
  faMagnifyingGlassArrowRight,
  faCircleXmark,
  faClipboard,
  faBahai,
  faFaceGrinWide,
  faShapes,
  faPerson,
  faImage,
  faRainbow,
  faHouse,
  faDice,
  faPenToSquare,
  faSackDollar,
  faFlask,
  faCircle,
  faCircleDot,
  faCircleMinus,
  faSquareXmark,
  faThumbtack,
  faPencil,
  faChartLine,
  faEye,
  faUserMinus,
  faUserPlus,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faAnglesRight,
  faAnglesLeft,
  faHammer,
  faDiamond
)
