/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentViewer: typeof import('./.vitepress/theme/components/ComponentViewer.vue')['default']
    IFeatherHome: typeof import('~icons/feather/home')['default']
    IFeatherSettings: typeof import('~icons/feather/settings')['default']
    IFeatherUser: typeof import('~icons/feather/user')['default']
    IHeroiconsCog: typeof import('~icons/heroicons/cog')['default']
    IHeroiconsHome: typeof import('~icons/heroicons/home')['default']
    IHeroiconsUser: typeof import('~icons/heroicons/user')['default']
    ILucideAlertTriangle: typeof import('~icons/lucide/alert-triangle')['default']
    ILucideCalendar: typeof import('~icons/lucide/calendar')['default']
    ILucideCheck: typeof import('~icons/lucide/check')['default']
    ILucideClock: typeof import('~icons/lucide/clock')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideEdit: typeof import('~icons/lucide/edit')['default']
    ILucideHeart: typeof import('~icons/lucide/heart')['default']
    ILucideHome: typeof import('~icons/lucide/home')['default']
    ILucideLink: typeof import('~icons/lucide/link')['default']
    ILucideMail: typeof import('~icons/lucide/mail')['default']
    ILucideMapPin: typeof import('~icons/lucide/map-pin')['default']
    ILucideMinus: typeof import('~icons/lucide/minus')['default']
    ILucidePhone: typeof import('~icons/lucide/phone')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideStar: typeof import('~icons/lucide/star')['default']
    ILucideTrash: typeof import('~icons/lucide/trash')['default']
    ILucideUpload: typeof import('~icons/lucide/upload')['default']
    ILucideUser: typeof import('~icons/lucide/user')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiClock: typeof import('~icons/mdi/clock')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiDownload: typeof import('~icons/mdi/download')['default']
    IMdiEmail: typeof import('~icons/mdi/email')['default']
    IMdiHeart: typeof import('~icons/mdi/heart')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiLink: typeof import('~icons/mdi/link')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMapMarker: typeof import('~icons/mdi/map-marker')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiPencil: typeof import('~icons/mdi/pencil')['default']
    IMdiPhone: typeof import('~icons/mdi/phone')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TwoColExample: typeof import('./.vitepress/theme/components/examples/TwoColExample.vue')['default']
  }
}
